/*
 * Telstra Programmable Network API
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package TelstraTPN;

import java.util.Objects;
import TelstraTPN.Billing;
import TelstraTPN.Role;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AuthValidatetokenResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-18T10:03:16.913+11:00")
public class AuthValidatetokenResponse {
  @SerializedName("company-name")
  private String companyName = null;

  @SerializedName("userid")
  private String userid = null;

  @SerializedName("internalid")
  private Integer internalid = null;

  @SerializedName("customerid")
  private String customerid = null;

  @SerializedName("customer-account")
  private String customerAccount = null;

  @SerializedName("billings")
  private List<Billing> billings = null;

  @SerializedName("roles")
  private List<Role> roles = null;

  public AuthValidatetokenResponse companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * 
   * @return companyName
  **/
  @ApiModelProperty(example = "Acme Corporation", value = "")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public AuthValidatetokenResponse userid(String userid) {
    this.userid = userid;
    return this;
  }

   /**
   * 
   * @return userid
  **/
  @ApiModelProperty(example = "321a5016-00a5-44ed-a749-4531ed89979a", value = "")
  public String getUserid() {
    return userid;
  }

  public void setUserid(String userid) {
    this.userid = userid;
  }

  public AuthValidatetokenResponse internalid(Integer internalid) {
    this.internalid = internalid;
    return this;
  }

   /**
   * 
   * @return internalid
  **/
  @ApiModelProperty(example = "353", value = "")
  public Integer getInternalid() {
    return internalid;
  }

  public void setInternalid(Integer internalid) {
    this.internalid = internalid;
  }

  public AuthValidatetokenResponse customerid(String customerid) {
    this.customerid = customerid;
    return this;
  }

   /**
   * 
   * @return customerid
  **/
  @ApiModelProperty(example = "bae254c1-3d78-4d68-8948-8b929c48e576", value = "")
  public String getCustomerid() {
    return customerid;
  }

  public void setCustomerid(String customerid) {
    this.customerid = customerid;
  }

  public AuthValidatetokenResponse customerAccount(String customerAccount) {
    this.customerAccount = customerAccount;
    return this;
  }

   /**
   * 
   * @return customerAccount
  **/
  @ApiModelProperty(example = "70012345", value = "")
  public String getCustomerAccount() {
    return customerAccount;
  }

  public void setCustomerAccount(String customerAccount) {
    this.customerAccount = customerAccount;
  }

  public AuthValidatetokenResponse billings(List<Billing> billings) {
    this.billings = billings;
    return this;
  }

  public AuthValidatetokenResponse addBillingsItem(Billing billingsItem) {
    if (this.billings == null) {
      this.billings = new ArrayList<Billing>();
    }
    this.billings.add(billingsItem);
    return this;
  }

   /**
   * 
   * @return billings
  **/
  @ApiModelProperty(value = "")
  public List<Billing> getBillings() {
    return billings;
  }

  public void setBillings(List<Billing> billings) {
    this.billings = billings;
  }

  public AuthValidatetokenResponse roles(List<Role> roles) {
    this.roles = roles;
    return this;
  }

  public AuthValidatetokenResponse addRolesItem(Role rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<Role>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * 
   * @return roles
  **/
  @ApiModelProperty(value = "")
  public List<Role> getRoles() {
    return roles;
  }

  public void setRoles(List<Role> roles) {
    this.roles = roles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthValidatetokenResponse authValidatetokenResponse = (AuthValidatetokenResponse) o;
    return Objects.equals(this.companyName, authValidatetokenResponse.companyName) &&
        Objects.equals(this.userid, authValidatetokenResponse.userid) &&
        Objects.equals(this.internalid, authValidatetokenResponse.internalid) &&
        Objects.equals(this.customerid, authValidatetokenResponse.customerid) &&
        Objects.equals(this.customerAccount, authValidatetokenResponse.customerAccount) &&
        Objects.equals(this.billings, authValidatetokenResponse.billings) &&
        Objects.equals(this.roles, authValidatetokenResponse.roles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, userid, internalid, customerid, customerAccount, billings, roles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthValidatetokenResponse {\n");
    
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    userid: ").append(toIndentedString(userid)).append("\n");
    sb.append("    internalid: ").append(toIndentedString(internalid)).append("\n");
    sb.append("    customerid: ").append(toIndentedString(customerid)).append("\n");
    sb.append("    customerAccount: ").append(toIndentedString(customerAccount)).append("\n");
    sb.append("    billings: ").append(toIndentedString(billings)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

