/*
 * Telstra Programmable Network API
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package TelstraTPN;

import java.util.Objects;
import TelstraTPN.Endpointlist;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Model100InventoryEndpointsCustomeruuidResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-19T14:16:29.049+11:00")
public class Model100InventoryEndpointsCustomeruuidResponse {
  @SerializedName("endpointlist")
  private List<Endpointlist> endpointlist = null;

  public Model100InventoryEndpointsCustomeruuidResponse endpointlist(List<Endpointlist> endpointlist) {
    this.endpointlist = endpointlist;
    return this;
  }

  public Model100InventoryEndpointsCustomeruuidResponse addEndpointlistItem(Endpointlist endpointlistItem) {
    if (this.endpointlist == null) {
      this.endpointlist = new ArrayList<Endpointlist>();
    }
    this.endpointlist.add(endpointlistItem);
    return this;
  }

   /**
   * 
   * @return endpointlist
  **/
  @ApiModelProperty(value = "")
  public List<Endpointlist> getEndpointlist() {
    return endpointlist;
  }

  public void setEndpointlist(List<Endpointlist> endpointlist) {
    this.endpointlist = endpointlist;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Model100InventoryEndpointsCustomeruuidResponse _100InventoryEndpointsCustomeruuidResponse = (Model100InventoryEndpointsCustomeruuidResponse) o;
    return Objects.equals(this.endpointlist, _100InventoryEndpointsCustomeruuidResponse.endpointlist);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpointlist);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Model100InventoryEndpointsCustomeruuidResponse {\n");
    
    sb.append("    endpointlist: ").append(toIndentedString(endpointlist)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

