/*
 * Telstra Programmable Network API
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package TelstraTPN;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Model100InventoryVnfVportRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-30T09:45:30.716+11:00")
public class Model100InventoryVnfVportRequest {
  @SerializedName("customeruuid")
  private String customeruuid = null;

  @SerializedName("vnfuuid")
  private String vnfuuid = null;

  @SerializedName("management_port")
  private Boolean managementPort = null;

  public Model100InventoryVnfVportRequest customeruuid(String customeruuid) {
    this.customeruuid = customeruuid;
    return this;
  }

   /**
   * 
   * @return customeruuid
  **/
  @ApiModelProperty(value = "")
  public String getCustomeruuid() {
    return customeruuid;
  }

  public void setCustomeruuid(String customeruuid) {
    this.customeruuid = customeruuid;
  }

  public Model100InventoryVnfVportRequest vnfuuid(String vnfuuid) {
    this.vnfuuid = vnfuuid;
    return this;
  }

   /**
   * 
   * @return vnfuuid
  **/
  @ApiModelProperty(value = "")
  public String getVnfuuid() {
    return vnfuuid;
  }

  public void setVnfuuid(String vnfuuid) {
    this.vnfuuid = vnfuuid;
  }

  public Model100InventoryVnfVportRequest managementPort(Boolean managementPort) {
    this.managementPort = managementPort;
    return this;
  }

   /**
   * 
   * @return managementPort
  **/
  @ApiModelProperty(value = "")
  public Boolean getManagementPort() {
    return managementPort;
  }

  public void setManagementPort(Boolean managementPort) {
    this.managementPort = managementPort;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Model100InventoryVnfVportRequest _100InventoryVnfVportRequest = (Model100InventoryVnfVportRequest) o;
    return Objects.equals(this.customeruuid, _100InventoryVnfVportRequest.customeruuid) &&
        Objects.equals(this.vnfuuid, _100InventoryVnfVportRequest.vnfuuid) &&
        Objects.equals(this.managementPort, _100InventoryVnfVportRequest.managementPort);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customeruuid, vnfuuid, managementPort);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Model100InventoryVnfVportRequest {\n");
    
    sb.append("    customeruuid: ").append(toIndentedString(customeruuid)).append("\n");
    sb.append("    vnfuuid: ").append(toIndentedString(vnfuuid)).append("\n");
    sb.append("    managementPort: ").append(toIndentedString(managementPort)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

