/*
 * Telstra Programmable Network API
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package TelstraTPN;

import java.util.Objects;
import TelstraTPN.Classification;
import TelstraTPN.Flavor;
import TelstraTPN.GlanceImage;
import TelstraTPN.Product;
import TelstraTPN.VnfTag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Object52
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-18T10:03:16.913+11:00")
public class Object52 {
  @SerializedName("brief_description")
  private String briefDescription = null;

  @SerializedName("buyers")
  private String buyers = null;

  @SerializedName("classifications")
  private List<Classification> classifications = null;

  @SerializedName("comments")
  private String comments = null;

  @SerializedName("create_at")
  private Integer createAt = null;

  @SerializedName("creator")
  private String creator = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("eos")
  private String eos = null;

  @SerializedName("flavors")
  private List<Flavor> flavors = null;

  @SerializedName("flavors_price")
  private String flavorsPrice = null;

  @SerializedName("glance_comments")
  private String glanceComments = null;

  @SerializedName("glance_image")
  private GlanceImage glanceImage = null;

  @SerializedName("glance_name")
  private String glanceName = null;

  @SerializedName("glance_properties")
  private String glanceProperties = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("image_format")
  private String imageFormat = null;

  @SerializedName("license_required")
  private Boolean licenseRequired = null;

  @SerializedName("logo")
  private String logo = null;

  @SerializedName("max_ports")
  private Integer maxPorts = null;

  @SerializedName("md5")
  private String md5 = null;

  @SerializedName("min_ports")
  private Integer minPorts = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("os_version")
  private String osVersion = null;

  @SerializedName("owner")
  private String owner = null;

  @SerializedName("product")
  private Product product = null;

  @SerializedName("publish_date")
  private String publishDate = null;

  @SerializedName("restrict_vnc_console")
  private Boolean restrictVncConsole = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("support_hot_plug")
  private Boolean supportHotPlug = null;

  @SerializedName("tags")
  private List<VnfTag> tags = null;

  @SerializedName("upload_at")
  private Integer uploadAt = null;

  @SerializedName("vendor_name")
  private String vendorName = null;

  @SerializedName("zero_day_config_spec")
  private String zeroDayConfigSpec = null;

  public Object52 briefDescription(String briefDescription) {
    this.briefDescription = briefDescription;
    return this;
  }

   /**
   * 
   * @return briefDescription
  **/
  @ApiModelProperty(example = "Quagga for general use", value = "")
  public String getBriefDescription() {
    return briefDescription;
  }

  public void setBriefDescription(String briefDescription) {
    this.briefDescription = briefDescription;
  }

  public Object52 buyers(String buyers) {
    this.buyers = buyers;
    return this;
  }

   /**
   * 
   * @return buyers
  **/
  @ApiModelProperty(value = "")
  public String getBuyers() {
    return buyers;
  }

  public void setBuyers(String buyers) {
    this.buyers = buyers;
  }

  public Object52 classifications(List<Classification> classifications) {
    this.classifications = classifications;
    return this;
  }

  public Object52 addClassificationsItem(Classification classificationsItem) {
    if (this.classifications == null) {
      this.classifications = new ArrayList<Classification>();
    }
    this.classifications.add(classificationsItem);
    return this;
  }

   /**
   * 
   * @return classifications
  **/
  @ApiModelProperty(value = "")
  public List<Classification> getClassifications() {
    return classifications;
  }

  public void setClassifications(List<Classification> classifications) {
    this.classifications = classifications;
  }

  public Object52 comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * 
   * @return comments
  **/
  @ApiModelProperty(value = "")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public Object52 createAt(Integer createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * 
   * @return createAt
  **/
  @ApiModelProperty(example = "1456314043", value = "")
  public Integer getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Integer createAt) {
    this.createAt = createAt;
  }

  public Object52 creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * 
   * @return creator
  **/
  @ApiModelProperty(example = "1f10c671-cd71-4467-b605-d150113629b9", value = "")
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public Object52 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 
   * @return description
  **/
  @ApiModelProperty(example = "Quagga router image with version 0.99.22.1", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Object52 eos(String eos) {
    this.eos = eos;
    return this;
  }

   /**
   * 
   * @return eos
  **/
  @ApiModelProperty(value = "")
  public String getEos() {
    return eos;
  }

  public void setEos(String eos) {
    this.eos = eos;
  }

  public Object52 flavors(List<Flavor> flavors) {
    this.flavors = flavors;
    return this;
  }

  public Object52 addFlavorsItem(Flavor flavorsItem) {
    if (this.flavors == null) {
      this.flavors = new ArrayList<Flavor>();
    }
    this.flavors.add(flavorsItem);
    return this;
  }

   /**
   * 
   * @return flavors
  **/
  @ApiModelProperty(value = "")
  public List<Flavor> getFlavors() {
    return flavors;
  }

  public void setFlavors(List<Flavor> flavors) {
    this.flavors = flavors;
  }

  public Object52 flavorsPrice(String flavorsPrice) {
    this.flavorsPrice = flavorsPrice;
    return this;
  }

   /**
   * 
   * @return flavorsPrice
  **/
  @ApiModelProperty(value = "")
  public String getFlavorsPrice() {
    return flavorsPrice;
  }

  public void setFlavorsPrice(String flavorsPrice) {
    this.flavorsPrice = flavorsPrice;
  }

  public Object52 glanceComments(String glanceComments) {
    this.glanceComments = glanceComments;
    return this;
  }

   /**
   * 
   * @return glanceComments
  **/
  @ApiModelProperty(value = "")
  public String getGlanceComments() {
    return glanceComments;
  }

  public void setGlanceComments(String glanceComments) {
    this.glanceComments = glanceComments;
  }

  public Object52 glanceImage(GlanceImage glanceImage) {
    this.glanceImage = glanceImage;
    return this;
  }

   /**
   * Get glanceImage
   * @return glanceImage
  **/
  @ApiModelProperty(value = "")
  public GlanceImage getGlanceImage() {
    return glanceImage;
  }

  public void setGlanceImage(GlanceImage glanceImage) {
    this.glanceImage = glanceImage;
  }

  public Object52 glanceName(String glanceName) {
    this.glanceName = glanceName;
    return this;
  }

   /**
   * 
   * @return glanceName
  **/
  @ApiModelProperty(example = "c9b2444c-239a-475b-af54-db9deccefca3", value = "")
  public String getGlanceName() {
    return glanceName;
  }

  public void setGlanceName(String glanceName) {
    this.glanceName = glanceName;
  }

  public Object52 glanceProperties(String glanceProperties) {
    this.glanceProperties = glanceProperties;
    return this;
  }

   /**
   * 
   * @return glanceProperties
  **/
  @ApiModelProperty(value = "")
  public String getGlanceProperties() {
    return glanceProperties;
  }

  public void setGlanceProperties(String glanceProperties) {
    this.glanceProperties = glanceProperties;
  }

  public Object52 id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "6", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Object52 imageFormat(String imageFormat) {
    this.imageFormat = imageFormat;
    return this;
  }

   /**
   * 
   * @return imageFormat
  **/
  @ApiModelProperty(example = "qcow2", value = "")
  public String getImageFormat() {
    return imageFormat;
  }

  public void setImageFormat(String imageFormat) {
    this.imageFormat = imageFormat;
  }

  public Object52 licenseRequired(Boolean licenseRequired) {
    this.licenseRequired = licenseRequired;
    return this;
  }

   /**
   * 
   * @return licenseRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isLicenseRequired() {
    return licenseRequired;
  }

  public void setLicenseRequired(Boolean licenseRequired) {
    this.licenseRequired = licenseRequired;
  }

  public Object52 logo(String logo) {
    this.logo = logo;
    return this;
  }

   /**
   * 
   * @return logo
  **/
  @ApiModelProperty(example = "https://marketplace-ms-production.s3.amazonaws.com/logos/cloud-8.jpg", value = "")
  public String getLogo() {
    return logo;
  }

  public void setLogo(String logo) {
    this.logo = logo;
  }

  public Object52 maxPorts(Integer maxPorts) {
    this.maxPorts = maxPorts;
    return this;
  }

   /**
   * 
   * @return maxPorts
  **/
  @ApiModelProperty(example = "8", value = "")
  public Integer getMaxPorts() {
    return maxPorts;
  }

  public void setMaxPorts(Integer maxPorts) {
    this.maxPorts = maxPorts;
  }

  public Object52 md5(String md5) {
    this.md5 = md5;
    return this;
  }

   /**
   * 
   * @return md5
  **/
  @ApiModelProperty(value = "")
  public String getMd5() {
    return md5;
  }

  public void setMd5(String md5) {
    this.md5 = md5;
  }

  public Object52 minPorts(Integer minPorts) {
    this.minPorts = minPorts;
    return this;
  }

   /**
   * 
   * @return minPorts
  **/
  @ApiModelProperty(example = "1", value = "")
  public Integer getMinPorts() {
    return minPorts;
  }

  public void setMinPorts(Integer minPorts) {
    this.minPorts = minPorts;
  }

  public Object52 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 
   * @return name
  **/
  @ApiModelProperty(example = "CSR1000v", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Object52 osVersion(String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

   /**
   * 
   * @return osVersion
  **/
  @ApiModelProperty(example = "Ubuntu 16.04", value = "")
  public String getOsVersion() {
    return osVersion;
  }

  public void setOsVersion(String osVersion) {
    this.osVersion = osVersion;
  }

  public Object52 owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * 
   * @return owner
  **/
  @ApiModelProperty(example = "d486321a-9a91-4879-8d7c-2fcf4506e33e", value = "")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public Object52 product(Product product) {
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @ApiModelProperty(value = "")
  public Product getProduct() {
    return product;
  }

  public void setProduct(Product product) {
    this.product = product;
  }

  public Object52 publishDate(String publishDate) {
    this.publishDate = publishDate;
    return this;
  }

   /**
   * 
   * @return publishDate
  **/
  @ApiModelProperty(value = "")
  public String getPublishDate() {
    return publishDate;
  }

  public void setPublishDate(String publishDate) {
    this.publishDate = publishDate;
  }

  public Object52 restrictVncConsole(Boolean restrictVncConsole) {
    this.restrictVncConsole = restrictVncConsole;
    return this;
  }

   /**
   * 
   * @return restrictVncConsole
  **/
  @ApiModelProperty(value = "")
  public Boolean isRestrictVncConsole() {
    return restrictVncConsole;
  }

  public void setRestrictVncConsole(Boolean restrictVncConsole) {
    this.restrictVncConsole = restrictVncConsole;
  }

  public Object52 status(String status) {
    this.status = status;
    return this;
  }

   /**
   * 
   * @return status
  **/
  @ApiModelProperty(example = "Published", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Object52 supportHotPlug(Boolean supportHotPlug) {
    this.supportHotPlug = supportHotPlug;
    return this;
  }

   /**
   * 
   * @return supportHotPlug
  **/
  @ApiModelProperty(value = "")
  public Boolean isSupportHotPlug() {
    return supportHotPlug;
  }

  public void setSupportHotPlug(Boolean supportHotPlug) {
    this.supportHotPlug = supportHotPlug;
  }

  public Object52 tags(List<VnfTag> tags) {
    this.tags = tags;
    return this;
  }

  public Object52 addTagsItem(VnfTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<VnfTag>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * 
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public List<VnfTag> getTags() {
    return tags;
  }

  public void setTags(List<VnfTag> tags) {
    this.tags = tags;
  }

  public Object52 uploadAt(Integer uploadAt) {
    this.uploadAt = uploadAt;
    return this;
  }

   /**
   * 
   * @return uploadAt
  **/
  @ApiModelProperty(example = "1456315518", value = "")
  public Integer getUploadAt() {
    return uploadAt;
  }

  public void setUploadAt(Integer uploadAt) {
    this.uploadAt = uploadAt;
  }

  public Object52 vendorName(String vendorName) {
    this.vendorName = vendorName;
    return this;
  }

   /**
   * 
   * @return vendorName
  **/
  @ApiModelProperty(example = "Cisco", value = "")
  public String getVendorName() {
    return vendorName;
  }

  public void setVendorName(String vendorName) {
    this.vendorName = vendorName;
  }

  public Object52 zeroDayConfigSpec(String zeroDayConfigSpec) {
    this.zeroDayConfigSpec = zeroDayConfigSpec;
    return this;
  }

   /**
   * 
   * @return zeroDayConfigSpec
  **/
  @ApiModelProperty(value = "")
  public String getZeroDayConfigSpec() {
    return zeroDayConfigSpec;
  }

  public void setZeroDayConfigSpec(String zeroDayConfigSpec) {
    this.zeroDayConfigSpec = zeroDayConfigSpec;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Object52 object52 = (Object52) o;
    return Objects.equals(this.briefDescription, object52.briefDescription) &&
        Objects.equals(this.buyers, object52.buyers) &&
        Objects.equals(this.classifications, object52.classifications) &&
        Objects.equals(this.comments, object52.comments) &&
        Objects.equals(this.createAt, object52.createAt) &&
        Objects.equals(this.creator, object52.creator) &&
        Objects.equals(this.description, object52.description) &&
        Objects.equals(this.eos, object52.eos) &&
        Objects.equals(this.flavors, object52.flavors) &&
        Objects.equals(this.flavorsPrice, object52.flavorsPrice) &&
        Objects.equals(this.glanceComments, object52.glanceComments) &&
        Objects.equals(this.glanceImage, object52.glanceImage) &&
        Objects.equals(this.glanceName, object52.glanceName) &&
        Objects.equals(this.glanceProperties, object52.glanceProperties) &&
        Objects.equals(this.id, object52.id) &&
        Objects.equals(this.imageFormat, object52.imageFormat) &&
        Objects.equals(this.licenseRequired, object52.licenseRequired) &&
        Objects.equals(this.logo, object52.logo) &&
        Objects.equals(this.maxPorts, object52.maxPorts) &&
        Objects.equals(this.md5, object52.md5) &&
        Objects.equals(this.minPorts, object52.minPorts) &&
        Objects.equals(this.name, object52.name) &&
        Objects.equals(this.osVersion, object52.osVersion) &&
        Objects.equals(this.owner, object52.owner) &&
        Objects.equals(this.product, object52.product) &&
        Objects.equals(this.publishDate, object52.publishDate) &&
        Objects.equals(this.restrictVncConsole, object52.restrictVncConsole) &&
        Objects.equals(this.status, object52.status) &&
        Objects.equals(this.supportHotPlug, object52.supportHotPlug) &&
        Objects.equals(this.tags, object52.tags) &&
        Objects.equals(this.uploadAt, object52.uploadAt) &&
        Objects.equals(this.vendorName, object52.vendorName) &&
        Objects.equals(this.zeroDayConfigSpec, object52.zeroDayConfigSpec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(briefDescription, buyers, classifications, comments, createAt, creator, description, eos, flavors, flavorsPrice, glanceComments, glanceImage, glanceName, glanceProperties, id, imageFormat, licenseRequired, logo, maxPorts, md5, minPorts, name, osVersion, owner, product, publishDate, restrictVncConsole, status, supportHotPlug, tags, uploadAt, vendorName, zeroDayConfigSpec);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Object52 {\n");
    
    sb.append("    briefDescription: ").append(toIndentedString(briefDescription)).append("\n");
    sb.append("    buyers: ").append(toIndentedString(buyers)).append("\n");
    sb.append("    classifications: ").append(toIndentedString(classifications)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    eos: ").append(toIndentedString(eos)).append("\n");
    sb.append("    flavors: ").append(toIndentedString(flavors)).append("\n");
    sb.append("    flavorsPrice: ").append(toIndentedString(flavorsPrice)).append("\n");
    sb.append("    glanceComments: ").append(toIndentedString(glanceComments)).append("\n");
    sb.append("    glanceImage: ").append(toIndentedString(glanceImage)).append("\n");
    sb.append("    glanceName: ").append(toIndentedString(glanceName)).append("\n");
    sb.append("    glanceProperties: ").append(toIndentedString(glanceProperties)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imageFormat: ").append(toIndentedString(imageFormat)).append("\n");
    sb.append("    licenseRequired: ").append(toIndentedString(licenseRequired)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    maxPorts: ").append(toIndentedString(maxPorts)).append("\n");
    sb.append("    md5: ").append(toIndentedString(md5)).append("\n");
    sb.append("    minPorts: ").append(toIndentedString(minPorts)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    publishDate: ").append(toIndentedString(publishDate)).append("\n");
    sb.append("    restrictVncConsole: ").append(toIndentedString(restrictVncConsole)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    supportHotPlug: ").append(toIndentedString(supportHotPlug)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    uploadAt: ").append(toIndentedString(uploadAt)).append("\n");
    sb.append("    vendorName: ").append(toIndentedString(vendorName)).append("\n");
    sb.append("    zeroDayConfigSpec: ").append(toIndentedString(zeroDayConfigSpec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

