/*
 * Telstra Programmable Network API
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package TelstraTPN;

import java.util.Objects;
import TelstraTPN.Classification;
import TelstraTPN.Flavor;
import TelstraTPN.GlanceImage;
import TelstraTPN.Product;
import TelstraTPN.VnfTag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Object50
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-30T09:45:30.716+11:00")
public class Object50 {
  @SerializedName("brief_description")
  private String briefDescription = null;

  @SerializedName("buyers")
  private String buyers = null;

  @SerializedName("classifications")
  private List<Classification> classifications = null;

  @SerializedName("comments")
  private String comments = null;

  @SerializedName("create_at")
  private Integer createAt = null;

  @SerializedName("creator")
  private String creator = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("eos")
  private String eos = null;

  @SerializedName("flavors")
  private List<Flavor> flavors = null;

  @SerializedName("flavors_price")
  private String flavorsPrice = null;

  @SerializedName("glance_comments")
  private String glanceComments = null;

  @SerializedName("glance_image")
  private GlanceImage glanceImage = null;

  @SerializedName("glance_name")
  private String glanceName = null;

  @SerializedName("glance_properties")
  private String glanceProperties = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("image_format")
  private String imageFormat = null;

  @SerializedName("license_required")
  private Boolean licenseRequired = null;

  @SerializedName("logo")
  private String logo = null;

  @SerializedName("max_ports")
  private Integer maxPorts = null;

  @SerializedName("md5")
  private String md5 = null;

  @SerializedName("min_ports")
  private Integer minPorts = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("os_version")
  private String osVersion = null;

  @SerializedName("owner")
  private String owner = null;

  @SerializedName("product")
  private Product product = null;

  @SerializedName("publish_date")
  private String publishDate = null;

  @SerializedName("restrict_vnc_console")
  private Boolean restrictVncConsole = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("support_hot_plug")
  private Boolean supportHotPlug = null;

  @SerializedName("tags")
  private List<VnfTag> tags = null;

  @SerializedName("upload_at")
  private Integer uploadAt = null;

  @SerializedName("vendor_name")
  private String vendorName = null;

  @SerializedName("zero_day_config_spec")
  private String zeroDayConfigSpec = null;

  public Object50 briefDescription(String briefDescription) {
    this.briefDescription = briefDescription;
    return this;
  }

   /**
   * 
   * @return briefDescription
  **/
  @ApiModelProperty(value = "")
  public String getBriefDescription() {
    return briefDescription;
  }

  public void setBriefDescription(String briefDescription) {
    this.briefDescription = briefDescription;
  }

  public Object50 buyers(String buyers) {
    this.buyers = buyers;
    return this;
  }

   /**
   * 
   * @return buyers
  **/
  @ApiModelProperty(value = "")
  public String getBuyers() {
    return buyers;
  }

  public void setBuyers(String buyers) {
    this.buyers = buyers;
  }

  public Object50 classifications(List<Classification> classifications) {
    this.classifications = classifications;
    return this;
  }

  public Object50 addClassificationsItem(Classification classificationsItem) {
    if (this.classifications == null) {
      this.classifications = new ArrayList<Classification>();
    }
    this.classifications.add(classificationsItem);
    return this;
  }

   /**
   * 
   * @return classifications
  **/
  @ApiModelProperty(value = "")
  public List<Classification> getClassifications() {
    return classifications;
  }

  public void setClassifications(List<Classification> classifications) {
    this.classifications = classifications;
  }

  public Object50 comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * 
   * @return comments
  **/
  @ApiModelProperty(value = "")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public Object50 createAt(Integer createAt) {
    this.createAt = createAt;
    return this;
  }

   /**
   * 
   * @return createAt
  **/
  @ApiModelProperty(value = "")
  public Integer getCreateAt() {
    return createAt;
  }

  public void setCreateAt(Integer createAt) {
    this.createAt = createAt;
  }

  public Object50 creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * 
   * @return creator
  **/
  @ApiModelProperty(value = "")
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public Object50 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Object50 eos(String eos) {
    this.eos = eos;
    return this;
  }

   /**
   * 
   * @return eos
  **/
  @ApiModelProperty(value = "")
  public String getEos() {
    return eos;
  }

  public void setEos(String eos) {
    this.eos = eos;
  }

  public Object50 flavors(List<Flavor> flavors) {
    this.flavors = flavors;
    return this;
  }

  public Object50 addFlavorsItem(Flavor flavorsItem) {
    if (this.flavors == null) {
      this.flavors = new ArrayList<Flavor>();
    }
    this.flavors.add(flavorsItem);
    return this;
  }

   /**
   * 
   * @return flavors
  **/
  @ApiModelProperty(value = "")
  public List<Flavor> getFlavors() {
    return flavors;
  }

  public void setFlavors(List<Flavor> flavors) {
    this.flavors = flavors;
  }

  public Object50 flavorsPrice(String flavorsPrice) {
    this.flavorsPrice = flavorsPrice;
    return this;
  }

   /**
   * 
   * @return flavorsPrice
  **/
  @ApiModelProperty(value = "")
  public String getFlavorsPrice() {
    return flavorsPrice;
  }

  public void setFlavorsPrice(String flavorsPrice) {
    this.flavorsPrice = flavorsPrice;
  }

  public Object50 glanceComments(String glanceComments) {
    this.glanceComments = glanceComments;
    return this;
  }

   /**
   * 
   * @return glanceComments
  **/
  @ApiModelProperty(value = "")
  public String getGlanceComments() {
    return glanceComments;
  }

  public void setGlanceComments(String glanceComments) {
    this.glanceComments = glanceComments;
  }

  public Object50 glanceImage(GlanceImage glanceImage) {
    this.glanceImage = glanceImage;
    return this;
  }

   /**
   * Get glanceImage
   * @return glanceImage
  **/
  @ApiModelProperty(value = "")
  public GlanceImage getGlanceImage() {
    return glanceImage;
  }

  public void setGlanceImage(GlanceImage glanceImage) {
    this.glanceImage = glanceImage;
  }

  public Object50 glanceName(String glanceName) {
    this.glanceName = glanceName;
    return this;
  }

   /**
   * 
   * @return glanceName
  **/
  @ApiModelProperty(value = "")
  public String getGlanceName() {
    return glanceName;
  }

  public void setGlanceName(String glanceName) {
    this.glanceName = glanceName;
  }

  public Object50 glanceProperties(String glanceProperties) {
    this.glanceProperties = glanceProperties;
    return this;
  }

   /**
   * 
   * @return glanceProperties
  **/
  @ApiModelProperty(value = "")
  public String getGlanceProperties() {
    return glanceProperties;
  }

  public void setGlanceProperties(String glanceProperties) {
    this.glanceProperties = glanceProperties;
  }

  public Object50 id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Object50 imageFormat(String imageFormat) {
    this.imageFormat = imageFormat;
    return this;
  }

   /**
   * 
   * @return imageFormat
  **/
  @ApiModelProperty(value = "")
  public String getImageFormat() {
    return imageFormat;
  }

  public void setImageFormat(String imageFormat) {
    this.imageFormat = imageFormat;
  }

  public Object50 licenseRequired(Boolean licenseRequired) {
    this.licenseRequired = licenseRequired;
    return this;
  }

   /**
   * 
   * @return licenseRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean getLicenseRequired() {
    return licenseRequired;
  }

  public void setLicenseRequired(Boolean licenseRequired) {
    this.licenseRequired = licenseRequired;
  }

  public Object50 logo(String logo) {
    this.logo = logo;
    return this;
  }

   /**
   * 
   * @return logo
  **/
  @ApiModelProperty(value = "")
  public String getLogo() {
    return logo;
  }

  public void setLogo(String logo) {
    this.logo = logo;
  }

  public Object50 maxPorts(Integer maxPorts) {
    this.maxPorts = maxPorts;
    return this;
  }

   /**
   * 
   * @return maxPorts
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxPorts() {
    return maxPorts;
  }

  public void setMaxPorts(Integer maxPorts) {
    this.maxPorts = maxPorts;
  }

  public Object50 md5(String md5) {
    this.md5 = md5;
    return this;
  }

   /**
   * 
   * @return md5
  **/
  @ApiModelProperty(value = "")
  public String getMd5() {
    return md5;
  }

  public void setMd5(String md5) {
    this.md5 = md5;
  }

  public Object50 minPorts(Integer minPorts) {
    this.minPorts = minPorts;
    return this;
  }

   /**
   * 
   * @return minPorts
  **/
  @ApiModelProperty(value = "")
  public Integer getMinPorts() {
    return minPorts;
  }

  public void setMinPorts(Integer minPorts) {
    this.minPorts = minPorts;
  }

  public Object50 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Object50 osVersion(String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

   /**
   * 
   * @return osVersion
  **/
  @ApiModelProperty(value = "")
  public String getOsVersion() {
    return osVersion;
  }

  public void setOsVersion(String osVersion) {
    this.osVersion = osVersion;
  }

  public Object50 owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * 
   * @return owner
  **/
  @ApiModelProperty(value = "")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public Object50 product(Product product) {
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @ApiModelProperty(value = "")
  public Product getProduct() {
    return product;
  }

  public void setProduct(Product product) {
    this.product = product;
  }

  public Object50 publishDate(String publishDate) {
    this.publishDate = publishDate;
    return this;
  }

   /**
   * 
   * @return publishDate
  **/
  @ApiModelProperty(value = "")
  public String getPublishDate() {
    return publishDate;
  }

  public void setPublishDate(String publishDate) {
    this.publishDate = publishDate;
  }

  public Object50 restrictVncConsole(Boolean restrictVncConsole) {
    this.restrictVncConsole = restrictVncConsole;
    return this;
  }

   /**
   * 
   * @return restrictVncConsole
  **/
  @ApiModelProperty(value = "")
  public Boolean getRestrictVncConsole() {
    return restrictVncConsole;
  }

  public void setRestrictVncConsole(Boolean restrictVncConsole) {
    this.restrictVncConsole = restrictVncConsole;
  }

  public Object50 status(String status) {
    this.status = status;
    return this;
  }

   /**
   * 
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Object50 supportHotPlug(Boolean supportHotPlug) {
    this.supportHotPlug = supportHotPlug;
    return this;
  }

   /**
   * 
   * @return supportHotPlug
  **/
  @ApiModelProperty(value = "")
  public Boolean getSupportHotPlug() {
    return supportHotPlug;
  }

  public void setSupportHotPlug(Boolean supportHotPlug) {
    this.supportHotPlug = supportHotPlug;
  }

  public Object50 tags(List<VnfTag> tags) {
    this.tags = tags;
    return this;
  }

  public Object50 addTagsItem(VnfTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<VnfTag>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * 
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public List<VnfTag> getTags() {
    return tags;
  }

  public void setTags(List<VnfTag> tags) {
    this.tags = tags;
  }

  public Object50 uploadAt(Integer uploadAt) {
    this.uploadAt = uploadAt;
    return this;
  }

   /**
   * 
   * @return uploadAt
  **/
  @ApiModelProperty(value = "")
  public Integer getUploadAt() {
    return uploadAt;
  }

  public void setUploadAt(Integer uploadAt) {
    this.uploadAt = uploadAt;
  }

  public Object50 vendorName(String vendorName) {
    this.vendorName = vendorName;
    return this;
  }

   /**
   * 
   * @return vendorName
  **/
  @ApiModelProperty(value = "")
  public String getVendorName() {
    return vendorName;
  }

  public void setVendorName(String vendorName) {
    this.vendorName = vendorName;
  }

  public Object50 zeroDayConfigSpec(String zeroDayConfigSpec) {
    this.zeroDayConfigSpec = zeroDayConfigSpec;
    return this;
  }

   /**
   * 
   * @return zeroDayConfigSpec
  **/
  @ApiModelProperty(value = "")
  public String getZeroDayConfigSpec() {
    return zeroDayConfigSpec;
  }

  public void setZeroDayConfigSpec(String zeroDayConfigSpec) {
    this.zeroDayConfigSpec = zeroDayConfigSpec;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Object50 object50 = (Object50) o;
    return Objects.equals(this.briefDescription, object50.briefDescription) &&
        Objects.equals(this.buyers, object50.buyers) &&
        Objects.equals(this.classifications, object50.classifications) &&
        Objects.equals(this.comments, object50.comments) &&
        Objects.equals(this.createAt, object50.createAt) &&
        Objects.equals(this.creator, object50.creator) &&
        Objects.equals(this.description, object50.description) &&
        Objects.equals(this.eos, object50.eos) &&
        Objects.equals(this.flavors, object50.flavors) &&
        Objects.equals(this.flavorsPrice, object50.flavorsPrice) &&
        Objects.equals(this.glanceComments, object50.glanceComments) &&
        Objects.equals(this.glanceImage, object50.glanceImage) &&
        Objects.equals(this.glanceName, object50.glanceName) &&
        Objects.equals(this.glanceProperties, object50.glanceProperties) &&
        Objects.equals(this.id, object50.id) &&
        Objects.equals(this.imageFormat, object50.imageFormat) &&
        Objects.equals(this.licenseRequired, object50.licenseRequired) &&
        Objects.equals(this.logo, object50.logo) &&
        Objects.equals(this.maxPorts, object50.maxPorts) &&
        Objects.equals(this.md5, object50.md5) &&
        Objects.equals(this.minPorts, object50.minPorts) &&
        Objects.equals(this.name, object50.name) &&
        Objects.equals(this.osVersion, object50.osVersion) &&
        Objects.equals(this.owner, object50.owner) &&
        Objects.equals(this.product, object50.product) &&
        Objects.equals(this.publishDate, object50.publishDate) &&
        Objects.equals(this.restrictVncConsole, object50.restrictVncConsole) &&
        Objects.equals(this.status, object50.status) &&
        Objects.equals(this.supportHotPlug, object50.supportHotPlug) &&
        Objects.equals(this.tags, object50.tags) &&
        Objects.equals(this.uploadAt, object50.uploadAt) &&
        Objects.equals(this.vendorName, object50.vendorName) &&
        Objects.equals(this.zeroDayConfigSpec, object50.zeroDayConfigSpec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(briefDescription, buyers, classifications, comments, createAt, creator, description, eos, flavors, flavorsPrice, glanceComments, glanceImage, glanceName, glanceProperties, id, imageFormat, licenseRequired, logo, maxPorts, md5, minPorts, name, osVersion, owner, product, publishDate, restrictVncConsole, status, supportHotPlug, tags, uploadAt, vendorName, zeroDayConfigSpec);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Object50 {\n");
    
    sb.append("    briefDescription: ").append(toIndentedString(briefDescription)).append("\n");
    sb.append("    buyers: ").append(toIndentedString(buyers)).append("\n");
    sb.append("    classifications: ").append(toIndentedString(classifications)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    createAt: ").append(toIndentedString(createAt)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    eos: ").append(toIndentedString(eos)).append("\n");
    sb.append("    flavors: ").append(toIndentedString(flavors)).append("\n");
    sb.append("    flavorsPrice: ").append(toIndentedString(flavorsPrice)).append("\n");
    sb.append("    glanceComments: ").append(toIndentedString(glanceComments)).append("\n");
    sb.append("    glanceImage: ").append(toIndentedString(glanceImage)).append("\n");
    sb.append("    glanceName: ").append(toIndentedString(glanceName)).append("\n");
    sb.append("    glanceProperties: ").append(toIndentedString(glanceProperties)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imageFormat: ").append(toIndentedString(imageFormat)).append("\n");
    sb.append("    licenseRequired: ").append(toIndentedString(licenseRequired)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    maxPorts: ").append(toIndentedString(maxPorts)).append("\n");
    sb.append("    md5: ").append(toIndentedString(md5)).append("\n");
    sb.append("    minPorts: ").append(toIndentedString(minPorts)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    publishDate: ").append(toIndentedString(publishDate)).append("\n");
    sb.append("    restrictVncConsole: ").append(toIndentedString(restrictVncConsole)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    supportHotPlug: ").append(toIndentedString(supportHotPlug)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    uploadAt: ").append(toIndentedString(uploadAt)).append("\n");
    sb.append("    vendorName: ").append(toIndentedString(vendorName)).append("\n");
    sb.append("    zeroDayConfigSpec: ").append(toIndentedString(zeroDayConfigSpec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

