/*
 * Telstra Programmable Network API
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package TelstraTPN;

import invalidPackageName.ApiCallback;
import invalidPackageName.ApiClient;
import invalidPackageName.ApiException;
import invalidPackageName.ApiResponse;
import invalidPackageName.Configuration;
import invalidPackageName.Pair;
import invalidPackageName.ProgressRequestBody;
import invalidPackageName.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import TelstraTPN.Topology;
import TelstraTPN.Ttms100TopologyTagObjectsResponse;
import TelstraTPN.Ttms100TopologyTagRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TopologiesApi {
    private ApiClient apiClient;

    public TopologiesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TopologiesApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for ttms100TopologyTagByTopotaguuidDelete
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call ttms100TopologyTagByTopotaguuidDeleteCall(String topotaguuid, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/ttms/1.0.0/topology_tag/{topotaguuid}/"
            .replaceAll("\\{" + "topotaguuid" + "\\}", apiClient.escapeString(topotaguuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call ttms100TopologyTagByTopotaguuidDeleteValidateBeforeCall(String topotaguuid, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'topotaguuid' is set
        if (topotaguuid == null) {
            throw new ApiException("Missing the required parameter 'topotaguuid' when calling ttms100TopologyTagByTopotaguuidDelete(Async)");
        }
        

        com.squareup.okhttp.Call call = ttms100TopologyTagByTopotaguuidDeleteCall(topotaguuid, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Delete a topology tag
     * Delete a topology tag
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void ttms100TopologyTagByTopotaguuidDelete(String topotaguuid) throws ApiException {
        ttms100TopologyTagByTopotaguuidDeleteWithHttpInfo(topotaguuid);
    }

    /**
     * Delete a topology tag
     * Delete a topology tag
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> ttms100TopologyTagByTopotaguuidDeleteWithHttpInfo(String topotaguuid) throws ApiException {
        com.squareup.okhttp.Call call = ttms100TopologyTagByTopotaguuidDeleteValidateBeforeCall(topotaguuid, null, null);
        return apiClient.execute(call);
    }

    /**
     * Delete a topology tag (asynchronously)
     * Delete a topology tag
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call ttms100TopologyTagByTopotaguuidDeleteAsync(String topotaguuid, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = ttms100TopologyTagByTopotaguuidDeleteValidateBeforeCall(topotaguuid, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for ttms100TopologyTagByTopotaguuidGet
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call ttms100TopologyTagByTopotaguuidGetCall(String topotaguuid, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/ttms/1.0.0/topology_tag/{topotaguuid}/"
            .replaceAll("\\{" + "topotaguuid" + "\\}", apiClient.escapeString(topotaguuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call ttms100TopologyTagByTopotaguuidGetValidateBeforeCall(String topotaguuid, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'topotaguuid' is set
        if (topotaguuid == null) {
            throw new ApiException("Missing the required parameter 'topotaguuid' when calling ttms100TopologyTagByTopotaguuidGet(Async)");
        }
        

        com.squareup.okhttp.Call call = ttms100TopologyTagByTopotaguuidGetCall(topotaguuid, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Get information about the specified topology tag
     * Get information about the specified topology tag
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @return Topology
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Topology ttms100TopologyTagByTopotaguuidGet(String topotaguuid) throws ApiException {
        ApiResponse<Topology> resp = ttms100TopologyTagByTopotaguuidGetWithHttpInfo(topotaguuid);
        return resp.getData();
    }

    /**
     * Get information about the specified topology tag
     * Get information about the specified topology tag
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @return ApiResponse&lt;Topology&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Topology> ttms100TopologyTagByTopotaguuidGetWithHttpInfo(String topotaguuid) throws ApiException {
        com.squareup.okhttp.Call call = ttms100TopologyTagByTopotaguuidGetValidateBeforeCall(topotaguuid, null, null);
        Type localVarReturnType = new TypeToken<Topology>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get information about the specified topology tag (asynchronously)
     * Get information about the specified topology tag
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call ttms100TopologyTagByTopotaguuidGetAsync(String topotaguuid, final ApiCallback<Topology> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = ttms100TopologyTagByTopotaguuidGetValidateBeforeCall(topotaguuid, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Topology>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for ttms100TopologyTagByTopotaguuidPut
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @param body  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call ttms100TopologyTagByTopotaguuidPutCall(String topotaguuid, Ttms100TopologyTagRequest body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/ttms/1.0.0/topology_tag/{topotaguuid}/"
            .replaceAll("\\{" + "topotaguuid" + "\\}", apiClient.escapeString(topotaguuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call ttms100TopologyTagByTopotaguuidPutValidateBeforeCall(String topotaguuid, Ttms100TopologyTagRequest body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'topotaguuid' is set
        if (topotaguuid == null) {
            throw new ApiException("Missing the required parameter 'topotaguuid' when calling ttms100TopologyTagByTopotaguuidPut(Async)");
        }
        

        com.squareup.okhttp.Call call = ttms100TopologyTagByTopotaguuidPutCall(topotaguuid, body, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Update a topology tag&#39;s name and/or description
     * Update a topology tag&#39;s name and/or description
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @param body  (optional)
     * @return Topology
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Topology ttms100TopologyTagByTopotaguuidPut(String topotaguuid, Ttms100TopologyTagRequest body) throws ApiException {
        ApiResponse<Topology> resp = ttms100TopologyTagByTopotaguuidPutWithHttpInfo(topotaguuid, body);
        return resp.getData();
    }

    /**
     * Update a topology tag&#39;s name and/or description
     * Update a topology tag&#39;s name and/or description
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @param body  (optional)
     * @return ApiResponse&lt;Topology&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Topology> ttms100TopologyTagByTopotaguuidPutWithHttpInfo(String topotaguuid, Ttms100TopologyTagRequest body) throws ApiException {
        com.squareup.okhttp.Call call = ttms100TopologyTagByTopotaguuidPutValidateBeforeCall(topotaguuid, body, null, null);
        Type localVarReturnType = new TypeToken<Topology>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Update a topology tag&#39;s name and/or description (asynchronously)
     * Update a topology tag&#39;s name and/or description
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @param body  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call ttms100TopologyTagByTopotaguuidPutAsync(String topotaguuid, Ttms100TopologyTagRequest body, final ApiCallback<Topology> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = ttms100TopologyTagByTopotaguuidPutValidateBeforeCall(topotaguuid, body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Topology>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for ttms100TopologyTagGet
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call ttms100TopologyTagGetCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/ttms/1.0.0/topology_tag";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call ttms100TopologyTagGetValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        

        com.squareup.okhttp.Call call = ttms100TopologyTagGetCall(progressListener, progressRequestListener);
        return call;

    }

    /**
     * List all topology tags
     * List all topology tags
     * @return List&lt;Topology&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<Topology> ttms100TopologyTagGet() throws ApiException {
        ApiResponse<List<Topology>> resp = ttms100TopologyTagGetWithHttpInfo();
        return resp.getData();
    }

    /**
     * List all topology tags
     * List all topology tags
     * @return ApiResponse&lt;List&lt;Topology&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<Topology>> ttms100TopologyTagGetWithHttpInfo() throws ApiException {
        com.squareup.okhttp.Call call = ttms100TopologyTagGetValidateBeforeCall(null, null);
        Type localVarReturnType = new TypeToken<List<Topology>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List all topology tags (asynchronously)
     * List all topology tags
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call ttms100TopologyTagGetAsync(final ApiCallback<List<Topology>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = ttms100TopologyTagGetValidateBeforeCall(progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<Topology>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for ttms100TopologyTagObjectsByTopotaguuidGet
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call ttms100TopologyTagObjectsByTopotaguuidGetCall(String topotaguuid, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/ttms/1.0.0/topology_tag/{topotaguuid}/objects/"
            .replaceAll("\\{" + "topotaguuid" + "\\}", apiClient.escapeString(topotaguuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call ttms100TopologyTagObjectsByTopotaguuidGetValidateBeforeCall(String topotaguuid, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'topotaguuid' is set
        if (topotaguuid == null) {
            throw new ApiException("Missing the required parameter 'topotaguuid' when calling ttms100TopologyTagObjectsByTopotaguuidGet(Async)");
        }
        

        com.squareup.okhttp.Call call = ttms100TopologyTagObjectsByTopotaguuidGetCall(topotaguuid, progressListener, progressRequestListener);
        return call;

    }

    /**
     * List objects for Topology
     * List all objects (Endpoints, Links, VPorts, etc.) associated with the topology tag.
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @return Ttms100TopologyTagObjectsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Ttms100TopologyTagObjectsResponse ttms100TopologyTagObjectsByTopotaguuidGet(String topotaguuid) throws ApiException {
        ApiResponse<Ttms100TopologyTagObjectsResponse> resp = ttms100TopologyTagObjectsByTopotaguuidGetWithHttpInfo(topotaguuid);
        return resp.getData();
    }

    /**
     * List objects for Topology
     * List all objects (Endpoints, Links, VPorts, etc.) associated with the topology tag.
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @return ApiResponse&lt;Ttms100TopologyTagObjectsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Ttms100TopologyTagObjectsResponse> ttms100TopologyTagObjectsByTopotaguuidGetWithHttpInfo(String topotaguuid) throws ApiException {
        com.squareup.okhttp.Call call = ttms100TopologyTagObjectsByTopotaguuidGetValidateBeforeCall(topotaguuid, null, null);
        Type localVarReturnType = new TypeToken<Ttms100TopologyTagObjectsResponse>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List objects for Topology (asynchronously)
     * List all objects (Endpoints, Links, VPorts, etc.) associated with the topology tag.
     * @param topotaguuid Unique identifier representing a specific topology tag (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call ttms100TopologyTagObjectsByTopotaguuidGetAsync(String topotaguuid, final ApiCallback<Ttms100TopologyTagObjectsResponse> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = ttms100TopologyTagObjectsByTopotaguuidGetValidateBeforeCall(topotaguuid, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Ttms100TopologyTagObjectsResponse>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for ttms100TopologyTagPost
     * @param body  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call ttms100TopologyTagPostCall(Ttms100TopologyTagRequest body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/ttms/1.0.0/topology_tag";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call ttms100TopologyTagPostValidateBeforeCall(Ttms100TopologyTagRequest body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        

        com.squareup.okhttp.Call call = ttms100TopologyTagPostCall(body, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Create a named topology tag
     * Create a named topology tag
     * @param body  (optional)
     * @return Topology
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Topology ttms100TopologyTagPost(Ttms100TopologyTagRequest body) throws ApiException {
        ApiResponse<Topology> resp = ttms100TopologyTagPostWithHttpInfo(body);
        return resp.getData();
    }

    /**
     * Create a named topology tag
     * Create a named topology tag
     * @param body  (optional)
     * @return ApiResponse&lt;Topology&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Topology> ttms100TopologyTagPostWithHttpInfo(Ttms100TopologyTagRequest body) throws ApiException {
        com.squareup.okhttp.Call call = ttms100TopologyTagPostValidateBeforeCall(body, null, null);
        Type localVarReturnType = new TypeToken<Topology>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Create a named topology tag (asynchronously)
     * Create a named topology tag
     * @param body  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call ttms100TopologyTagPostAsync(Ttms100TopologyTagRequest body, final ApiCallback<Topology> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = ttms100TopologyTagPostValidateBeforeCall(body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Topology>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
