/*
 * Telstra Programmable Network API
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package TelstraTPN;

import java.util.Objects;
import TelstraTPN.Vportvalue;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Vport
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-19T14:16:29.049+11:00")
public class Vport {
  @SerializedName("status")
  private String status = null;

  @SerializedName("bandwidth")
  private Integer bandwidth = null;

  @SerializedName("interfacesequence")
  private Integer interfacesequence = null;

  @SerializedName("vporttype")
  private String vporttype = null;

  @SerializedName("vportuuid")
  private String vportuuid = null;

  @SerializedName("vportvalue")
  private Vportvalue vportvalue = null;

  public Vport status(String status) {
    this.status = status;
    return this;
  }

   /**
   * 
   * @return status
  **/
  @ApiModelProperty(example = "deployed", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Vport bandwidth(Integer bandwidth) {
    this.bandwidth = bandwidth;
    return this;
  }

   /**
   * 
   * @return bandwidth
  **/
  @ApiModelProperty(example = "0", value = "")
  public Integer getBandwidth() {
    return bandwidth;
  }

  public void setBandwidth(Integer bandwidth) {
    this.bandwidth = bandwidth;
  }

  public Vport interfacesequence(Integer interfacesequence) {
    this.interfacesequence = interfacesequence;
    return this;
  }

   /**
   * 
   * @return interfacesequence
  **/
  @ApiModelProperty(example = "0", value = "")
  public Integer getInterfacesequence() {
    return interfacesequence;
  }

  public void setInterfacesequence(Integer interfacesequence) {
    this.interfacesequence = interfacesequence;
  }

  public Vport vporttype(String vporttype) {
    this.vporttype = vporttype;
    return this;
  }

   /**
   * 
   * @return vporttype
  **/
  @ApiModelProperty(example = "vlan", value = "")
  public String getVporttype() {
    return vporttype;
  }

  public void setVporttype(String vporttype) {
    this.vporttype = vporttype;
  }

  public Vport vportuuid(String vportuuid) {
    this.vportuuid = vportuuid;
    return this;
  }

   /**
   * 
   * @return vportuuid
  **/
  @ApiModelProperty(example = "e62716f5-cc68-40e7-b97e-f1e3d1bda9a8", value = "")
  public String getVportuuid() {
    return vportuuid;
  }

  public void setVportuuid(String vportuuid) {
    this.vportuuid = vportuuid;
  }

  public Vport vportvalue(Vportvalue vportvalue) {
    this.vportvalue = vportvalue;
    return this;
  }

   /**
   * Get vportvalue
   * @return vportvalue
  **/
  @ApiModelProperty(value = "")
  public Vportvalue getVportvalue() {
    return vportvalue;
  }

  public void setVportvalue(Vportvalue vportvalue) {
    this.vportvalue = vportvalue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vport vport = (Vport) o;
    return Objects.equals(this.status, vport.status) &&
        Objects.equals(this.bandwidth, vport.bandwidth) &&
        Objects.equals(this.interfacesequence, vport.interfacesequence) &&
        Objects.equals(this.vporttype, vport.vporttype) &&
        Objects.equals(this.vportuuid, vport.vportuuid) &&
        Objects.equals(this.vportvalue, vport.vportvalue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, bandwidth, interfacesequence, vporttype, vportuuid, vportvalue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vport {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    bandwidth: ").append(toIndentedString(bandwidth)).append("\n");
    sb.append("    interfacesequence: ").append(toIndentedString(interfacesequence)).append("\n");
    sb.append("    vporttype: ").append(toIndentedString(vporttype)).append("\n");
    sb.append("    vportuuid: ").append(toIndentedString(vportuuid)).append("\n");
    sb.append("    vportvalue: ").append(toIndentedString(vportvalue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

